###  <font color='green' size=5> HW #3: What is SoftMax Function?
</font> 

**Customer Analytics** <br>
**ANLT 274** <br>
**November 10, 2018** <br>
<br>

<font color='green' size=4> By: Ali Taheri</font>

SoftMax is an activation function that turns numbers (logits) in the output of neural network into probabilities that sum to one, so we can classify an input to discrete classes unlike the commonly used logistic regression, which can only perform binary classifications. For this target, we would calculate e to the power of every logit and divide all of them by summation of all. This method would preserve the ratio of vectors as opposed to squashing the end-points with a sigmoid as the values saturate. With SoftMax, the biggest value in a vector would have the biggest contribution to output vector too. <br>
Let us consider a neural network with following label data: <br>
[1,0,0] #man   <br>
[0,1,0] #woman   <br>
[0,0,1] #bisexual  <br>
<br>
Input to activation layer is as below: <br>
[5 , 3 , 1.5] <br>
Now, we calculate probabilities by SoftMax:

In [29]:
import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    return np.round(np.exp(x) / np.sum(np.exp(x)),2)

def softmax_1(x):
    """Compute softmax values for each sets of scores in x with subtraction of maximum value."""
    e_x = np.exp(x - np.max(x))
    return np.round(e_x / e_x.sum(),2)

We apply both function to scores:

In [34]:
scores = [5, 3.0, 1.5]
print(softmax(scores))
print(softmax_1(scores))

[0.86 0.12 0.03]
[0.86 0.12 0.03]


We see both outputs are the same as we expected because we divided both of numerator and denominator to the maximum value of logits. We do this for more stability in case of huge numbers and the chance of overflow. <br>

The output probabilities are saying 86% sure it is a man, 12% a woman and 3% a bisexual. <br>
Now, let us have a simple normalization:

In [35]:
np.round(scores / np.sum(scores) , 2)

array([0.53, 0.32, 0.16])